version: '3.4'

networks:
  clashroyaleapp:

services:
  clashroyalerestapi:
    image: clashroyalerestapi:latest
    container_name: clashroyalerestapi
    build:
      context: .
      dockerfile: ClashRoyaleRestAPI.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:8000
      - ASPNETCORE_ENVIRONMENT= Development
      - ASPNETCORE_HTTP_PORTS= 8000
      - ASPNETCORE_HTTPS_PORTS= 5001
    ports:
      - "8000:80"
      - "5001:443"
    depends_on: 
      - clashroyalerestapi.database
      - clashroyalerestapi.cache
    networks: 
      - clashroyaleapp
  
  clashroyalerestapi.database:
    image: postgres:16
    container_name: clashroyalerestapi.db
    environment:
      POSTGRES_USER: "clashroyalerestapi"
      POSTGRES_PASSWORD: "clashroyalerestapi"
      POSTGRES_DB: "clashroyalerestapi_db"
    volumes:
      - ./.containers/clashroyalerestapi-db:/var/lib/postgresql/data
    networks:
      - clashroyaleapp
  
  clashroyalerestapi.cache:
    image: redis:latest
    container_name: clashroyalerestapi.cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - clashroyaleapp